// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmlLnF1VCnrQb5lB6HT9S4GpP_BG1VwrU',
    appId: '1:746038299558:web:a4ee8972bf8117f848dd67',
    messagingSenderId: '746038299558',
    projectId: 'mohammed-768cb',
    authDomain: 'mohammed-768cb.firebaseapp.com',
    storageBucket: 'mohammed-768cb.appspot.com',
    measurementId: 'G-TZ6RYYL5EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9rTJEnF8049_IWGOF8hoRPSso12uNTJc',
    appId: '1:746038299558:android:c43cbc068fc2b89948dd67',
    messagingSenderId: '746038299558',
    projectId: 'mohammed-768cb',
    storageBucket: 'mohammed-768cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSdiYJcKRgvS01UMmezmzYN8oWUomDIE',
    appId: '1:746038299558:ios:f8c1771e601d5c5d48dd67',
    messagingSenderId: '746038299558',
    projectId: 'mohammed-768cb',
    storageBucket: 'mohammed-768cb.appspot.com',
    iosClientId: '746038299558-khkqftmae9d12j780510li80847ji8j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystoreapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSdiYJcKRgvS01UMmezmzYN8oWUomDIE',
    appId: '1:746038299558:ios:f8c1771e601d5c5d48dd67',
    messagingSenderId: '746038299558',
    projectId: 'mohammed-768cb',
    storageBucket: 'mohammed-768cb.appspot.com',
    iosClientId: '746038299558-khkqftmae9d12j780510li80847ji8j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystoreapp',
  );
}
